from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import httpx
import json

app = FastAPI(title="RAG Pipeline API", description="Agents R3 (Retrieval), R4 (Generator), R5 (Formatter)")

class RAGQuery(BaseModel):
    query: str
    mode: str = "patient" # 'patient' or 'doctor'

# Mock Supabase URL and OpenRouter Key
SUPABASE_URL = "https://your-project.supabase.co/rest/v1/rpc/match_documents"
OPENROUTER_API_KEY = "sk-or-v1-..."

@app.post("/ask")
async def ask_rag_pipeline(req: RAGQuery):
    try:
        # ==========================================
        # AGENT R3: Retrieval Engine
        # ==========================================
        # In a real scenario, we'd embed the query using sentence-transformers,
        # then POST to Supabase pgvector function to get top 5 passages.
        # Here we mock the retrieved context:
        mock_retrieved_context = [
            {"content": "For mild fever and chest pain, assess for other red flags. Refer to WHO guidelines Chapter 4.", "source": "WHO IMCI Guide"},
            {"content": "Ibuprofen is contraindicated in patients with severe asthma.", "source": "Indian National Formulary"}
        ]
        
        # ==========================================
        # AGENT R4: Grounded Generator
        # ==========================================
        # We call OpenRouter API (Gemma-4-31b) with the context and query.
        system_prompt = (
            "You are Anvaya, a medical information assistant. Answer ONLY based on the provided reference passages. "
            "Never prescribe. Cite sources like [Source: X]. "
            "Use simple language." if req.mode == "patient" else "Use clinical terminology."
        )
        
        context_str = "\n".join([f"[{p['source']}]: {p['content']}" for p in mock_retrieved_context])
        
        # Mocking the OpenRouter HTTP Call
        '''
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers={"Authorization": f"Bearer {OPENROUTER_API_KEY}"},
                json={
                    "model": "google/gemma-4-31b-it:free",
                    "messages": [
                        {"role": "system", "content": system_prompt + "\n\nReferences:\n" + context_str},
                        {"role": "user", "content": req.query}
                    ]
                }
            )
            llm_response = resp.json()['choices'][0]['message']['content']
        '''
        llm_response = f"Based on the provided information, if you have a fever and chest pain, you should assess for other signs [Source: WHO IMCI Guide]. I cannot prescribe medications, but note that ibuprofen is contraindicated for severe asthma [Source: Indian National Formulary]."
        
        # ==========================================
        # AGENT R5: Response Formatter
        # ==========================================
        # Formats the text, potentially translates it, and adds UI metadata
        formatted_response = {
            "answer_text": llm_response,
            "citations": [p['source'] for p in mock_retrieved_context],
            "audio_url": None, # Would be generated by R1 TTS
            "urgency_banner": False,
            "suggested_followups": ["What are the other red flags?", "When should I see a doctor?"]
        }
        
        return {
            "status": "success",
            "data": formatted_response
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8031)
