from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import httpx
import os

# Load environment variables from .env file if present
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed; rely on system env vars

app = FastAPI(title="RAG Pipeline API", description="Agents R3 (Retrieval), R4 (Generator), R5 (Formatter)")

# Allow frontend origins to call this agent directly (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class RAGQuery(BaseModel):
    query: str
    mode: str = "patient"  # 'patient' or 'doctor'

# Load keys from environment — fall back gracefully to mock mode
SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")

_USE_REAL_LLM = bool(OPENROUTER_API_KEY and not OPENROUTER_API_KEY.startswith("sk-or-v1-..."))

@app.get("/health")
async def health():
    return {"status": "ok", "mode": "live" if _USE_REAL_LLM else "demo"}

@app.post("/ask")
async def ask_rag_pipeline(req: RAGQuery):
    try:
        # ==========================================
        # AGENT R3: Retrieval Engine
        # ==========================================
        # In production: embed query → pgvector search on Supabase.
        # Demo mode: return mock retrieved context.
        mock_retrieved_context = [
            {"content": "For mild fever and chest pain, assess for other red flags. Refer to WHO guidelines Chapter 4.", "source": "WHO IMCI Guide"},
            {"content": "Ibuprofen is contraindicated in patients with severe asthma.", "source": "Indian National Formulary"},
        ]

        # ==========================================
        # AGENT R4: Grounded Generator
        # ==========================================
        system_prompt = (
            "You are Anvaya, a medical information assistant. Answer ONLY based on the provided reference passages. "
            "Never prescribe. Cite sources like [Source: X]. "
            + ("Use simple language for patients." if req.mode == "patient" else "Use clinical terminology for doctors.")
        )

        context_str = "\n".join([f"[{p['source']}]: {p['content']}" for p in mock_retrieved_context])
        llm_response = None

        if _USE_REAL_LLM:
            try:
                async with httpx.AsyncClient(timeout=20) as client:
                    resp = await client.post(
                        "https://openrouter.ai/api/v1/chat/completions",
                        headers={"Authorization": f"Bearer {OPENROUTER_API_KEY}"},
                        json={
                            "model": "google/gemma-4-31b-it:free",
                            "messages": [
                                {"role": "system", "content": system_prompt + "\n\nReferences:\n" + context_str},
                                {"role": "user", "content": req.query},
                            ],
                        },
                    )
                    data = resp.json()
                    llm_response = data["choices"][0]["message"]["content"]
            except Exception as llm_err:
                # Live call failed — fall through to mock response
                llm_response = None

        if llm_response is None:
            # Demo / fallback response
            llm_response = (
                f"Based on the available references: {context_str}\n\n"
                f"For your question about '{req.query}': please consult a qualified health worker for personalised advice. "
                "[Source: WHO IMCI Guide, Indian National Formulary]"
            )

        # ==========================================
        # AGENT R5: Response Formatter
        # ==========================================
        formatted_response = {
            "answer_text": llm_response,
            "citations": [p["source"] for p in mock_retrieved_context],
            "audio_url": None,  # Generated by R1 TTS in production
            "urgency_banner": False,
            "suggested_followups": [
                "What are the warning signs I should watch for?",
                "When should I go to hospital immediately?",
            ],
        }

        return {"status": "success", "data": formatted_response}

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8031)
